# Using ALBERT to classify text

In [8]:
pip install keras

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 17.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 41.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 736.8/736.8 kB 20.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.6/589.6 kB 16.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [9]:
pip install keras_hub

Note: you may need to restart the kernel to use updated packages.


In [12]:
pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.6/259.6 MB 54.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 21.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 48.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 55.4 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 45.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 36.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 50.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.2
    Uninstalling numpy-2.1.2:
      Successfully uninstalled numpy-2.1.2
  Attempting uninstall: ml-dtypes
    Found existing installation: ml_dtypes 0.5.0
    Uninstalling ml_dtypes-0.5.0:
      Successfully uninstalled ml_dtypes-0.5.0
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install tensorflow-text

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 6.9 MB/s eta 0:00:00a 0:00:01m
Note: you may need to restart the kernel to use updated packages.


In [1]:
import keras_hub

2024-11-12 20:25:27.817281: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/Silvia/Desktop/kaggle_project/kaggle/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# Unbatched input.
tokenizer = keras_hub.models.AlbertTokenizer.from_preset(
    "albert_base_en_uncased",
)
tokenizer("The quick brown fox jumped.")

100%|██████████| 742k/742k [00:00<00:00, 1.29MB/s]


<tf.Tensor: shape=(8,), dtype=int32, numpy=array([  13,    1,  438, 2231,  886, 2385, 4298,    9], dtype=int32)>

In [3]:
# Batched input.
tokenizer(["The quick brown fox jumped.", "The fox slept."])

[[13, 1, 438, 2231, 886, 2385, 4298, 9], [13, 1, 438, 2385, 7132, 9]]

In [4]:
# Detokenization.
tokenizer.detokenize(tokenizer("The quick brown fox jumped."))

' ⁇ he quick brown fox jumped.'

In [8]:
import tensorflow as tf
import io

In [ ]:
#https://keras.io/api/keras_nlp/models/albert/albert_tokenizer/
tokenizer = keras_hub.tokenizers.Tokenizer.from_preset("albert_extra_large_en_uncased")

100%|██████████| 610/610 [00:00<00:00, 344kB/s]


100%|██████████| 406/406 [00:00<00:00, 357kB/s]


100%|██████████| 742k/742k [00:00<00:00, 1.29MB/s]


In [26]:
# Tokenize some input.
tokenizer("The quick brown fox tripped.")

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([   13,     1,   438,  2231,   886,  2385, 23606,     9],
      dtype=int32)>

In [28]:
# Detokenize some input.
tokenizer.detokenize([ 13,     1,   438,  2231,   886,  2385, 23606,     9])

' ⁇ he quick brown fox tripped.'

In [29]:
tokenizer.detokenize(tokenizer("The quick brown fox jumped."))

' ⁇ he quick brown fox jumped.'